---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyPipeline:
    Type: AWS::CodePipeline::Academy_Back
    Properties:
      ArtifactStore:
        Type: S3
        Location: codepipeline-sa-east-1-897622276299
      RoleArn: arn:aws:iam::336640966276:role/service-role/AWSCodePipelineServiceRole-sa-east-1-Academy_Back
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "2"
              Configuration:
                Owner: reinnerh
                Repo: TodoListAcademyApi
                Branch: main
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: TodoListAcademyAPI
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: "1"
              Configuration:
                ApplicationName: AcademyBack_API
                DeploymentGroupName: AcademyBack_API
              InputArtifacts:
                - Name: BuildOutput
